"""Strategy signal models."""

from datetime import datetime
from decimal import Decimal
from typing import Literal, Optional

from pydantic import BaseModel, Field, model_validator


class Signal(BaseModel):
    """
    Trading signal generated by a strategy.
    
    Signals represent the strategy's intent to buy, sell, or hold.
    For buys, specify the dollar amount. For sells, specify the quantity.
    
    Attributes:
        symbol: Trading symbol
        action: Action to take - "buy", "sell", or "hold"
        amount: Dollar amount for buy orders
        quantity: Share quantity for sell orders
        reason: Human-readable explanation for the signal
        timestamp: When the signal was generated
        confidence: Signal confidence (0.0 to 1.0)
    """
    
    symbol: str = Field(..., description="Trading symbol")
    action: Literal["buy", "sell", "hold"] = Field(..., description="Signal action")
    amount: Optional[Decimal] = Field(
        default=None, 
        description="Dollar amount for buy orders",
        ge=0
    )
    quantity: Optional[Decimal] = Field(
        default=None, 
        description="Share quantity for sell orders",
        ge=0
    )
    reason: str = Field(..., description="Reason for the signal")
    timestamp: datetime = Field(..., description="Signal timestamp")
    confidence: float = Field(
        default=1.0, 
        description="Signal confidence",
        ge=0.0,
        le=1.0
    )
    
    @model_validator(mode="after")
    def validate_amount_or_quantity(self) -> "Signal":
        """Validate that buy signals have amount and sell signals have quantity."""
        if self.action == "buy" and self.amount is None:
            # Allow buy signals without amount for hold or informational signals
            pass
        if self.action == "sell" and self.quantity is None:
            # Allow sell signals without quantity for informational signals
            pass
        return self
    
    def __str__(self) -> str:
        if self.action == "buy" and self.amount:
            return f"Signal({self.action.upper()} ${self.amount} of {self.symbol}: {self.reason})"
        elif self.action == "sell" and self.quantity:
            return f"Signal({self.action.upper()} {self.quantity} shares of {self.symbol}: {self.reason})"
        else:
            return f"Signal({self.action.upper()} {self.symbol}: {self.reason})"
